config/routes.rb
Rails.application.routes.draw do

 
  root 'home#index'
  post 'search' => 'main#search'
  get 'show/:id' => 'main#show'
  # get 'show/:id' => 'main#show'
  
  resources :actions
  resources :matters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/action.rb
class Action < ApplicationRecord
	has_and_belongs_to_many :matters
end

app/models/actions_matters.rb
class ActionsMatters < ApplicationRecord
  belongs_to :action
  belongs_to :matter
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/matter.rb
class Matter < ApplicationRecord
	has_and_belongs_to_many :actions
end

app/models/matters_actions.rb
class MattersActions < ApplicationRecord
  belongs_to :matter
  belongs_to :action
end

app/models/park.rb
class Park < ApplicationRecord
	has_and_belongs_to_many :rangers
end

app/models/parks_rangers.rb
class ParksRangers < ApplicationRecord
  belongs_to :park
  belongs_to :ranger
end

app/models/ranger.rb
class Ranger < ApplicationRecord
	has_and_belongs_to_many :parks
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
def index
    @actions = Action.all.order(:title)
  end

  def show
    @action = Action.find(params[:id])
  end

  def new
    @action = Action.new
    @actions = Action.all 
  end

  def create
    Action.create(action_params)
    redirect_to actions_path
  end

  def destroy
    @action_to_delete = Action.find(params[:id])
    @action_to_delete.matters.clear
    @action_to_delete.delete
    redirect_to actions_path
  end

  def update
    Action.find(params[:id]).update(action_params)
    redirect_to matters_path
  end


  private

  def action_params
    params.require(:action).permit(:title, :description, :open, :completed, :duration, :location, :matter_ids => [])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/main_controller.rb
require 'httparty'
require 'json'

class MainController < ApplicationController
	include HTTParty, MainHelper

  def index
  	flash.now[:info] = 'welcome!'
  end

  def search
  	@res = HTTParty.get('https://itunes.apple.com/search?term=' + verify_input(params[:artist]))
  	@results = JSON.parse(@res.body)['results']

  	if @results.length <= 0 
  		flash.now[:warning] = "Your search returned no results, please check the artist name and try again."
  	end
  	puts 'RESULTS:'
  	puts @results
  end

  def show
  	@res = HTTParty.get('https://itunes.apple.com/lookup?entity=song&id=' + params[:id])
  	@single_track = JSON.parse(@res.body)['results']
  end

end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
def index
  	@matters = Matter.all.order(:title)
  end

  def new
  	@matter = Matter.new
  	@actions = Action.all.order(:title)

  end

  def edit
    @matter = Matter.find(params[:id])
  end

  def show
  	@matter = Matter.find(params[:id])
  end

  def create
  	Matter.create(matter_params)
  	redirect_to matters_path
  end

  def destroy
  	@matter_to_delete = Matter.find(params[:id])
  	@matter_to_delete.actions.clear
  	@matter_to_delete.delete
  	redirect_to matter_path
  end

  def update
    Matter.find(params[:id]).update(matter_params)
    redirect_to matters_path
  end


  private

  def matter_params
  	params.require(:matter).permit(:title, :description, :open, :close, :due, :action_ids => [])
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def index
  	@parks = Park.all.order(:name)
  end

  def new
  	@park = Park.new
  	@rangers = Ranger.all.order(:name)

  end

  def edit
    @park = Park.find(params[:id])
  end

  def show
  	@park = Park.find(params[:id])
  end

  def create
  	Park.create(park_params)
  	redirect_to parks_path
  end

  def destroy
  	@park_to_delete = Park.find(params[:id])
  	@park_to_delete.rangers.clear
  	@park_to_delete.delete
  	redirect_to parks_path
  end

  def update
    Park.find(params[:id]).update(park_params)
    redirect_to parks_path
  end


  private

  def park_params
  	params.require(:park).permit(:name, :description, :picture, :ranger_ids => [])
  end
end

app/controllers/rangers_controller.rb
class RangersController < ApplicationController
  def index
  	@rangers = Ranger.all.order(:name)
  end

  def show
  	@ranger = Ranger.find(params[:id])
  end

  def new
  	@ranger = Ranger.new
  	@parks = Park.all 
  end

  def create
  	Ranger.create(ranger_params)
  	redirect_to rangers_path
  end

  def destroy
    @ranger_to_delete = Ranger.find(params[:id])
    @ranger_to_delete.parks.clear
    @ranger_to_delete.delete
    redirect_to rangers_path
  end

  def update
    Ranger.find(params[:id]).update(ranger_params)
    redirect_to parks_path
  end


  private

  def ranger_params
  	params.require(:ranger).permit(:name, :park_ids => [])
  end


end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_helper.rb
module MainHelper
	def verify_input(artist)
		return artist.gsub(/[^0-9a-z \.]/i, '')
	end
end

app/helpers/matter_helper.rb
module MatterHelper
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/rangers_helper.rb
module RangersHelper
end

app/views/actions/index.html.erb
<h1 class="text-center">Activities</h1>
<h3 class="text-center"></h3>

<div class="container">
  <% @actions.each do |r| %>
    <div class="alert alert-info">
      <a href="/actions/<%= r.id %>">
        Action <%= r.title %>
      </a>
    </div>

  <% end %>
</div>

app/views/actions/new.html.erb
<h1 class="text-center">New Activity</h1>

<div class="continer">
<%= form_for @action do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, :class => "form-control" %>
	</div>
		<%= f.collection_check_boxes :matter_ids, @matters, :id, :title %>
		<%= f.submit :class => "btn btn-primary" %>

<% end %>
</div>

app/views/actions/show.html.erb
<h1 class="text-center">Activity <%= @action.title %> Details</h1>
<h4 class="text-center">Activity <%= @action.title %> is available to relate to all Matters</h4>

<h2 class="text-center">Matters associated with <%= @action.name %></h2>

<div class="container text-center">
	<% if @action.matters.length > 0 %>
		<% @action.matters.each do |p| %>
			<div class="alert alert-info">
				<h3>
					<a href="/matters/<%= p.id %>"><%= p.name %></a>
				</h3>	
			</div>
		<% end %>
	<% else %>
		<div class="alert alert-info">
			Activity <%= @action.title %> is still waiting to be assigned to a Matter.
		</div>
		</div>
		<h2>ACTION CRUD:</h2>
			<%= link_to 'Update this Action?', edit_action_path(@action), method: :get, :class => "btn btn-warning" %>
			<%= link_to 'Delete This Action?', action_path(@action), method: :delete, :class => "btn btn-danger" %>
	</div>

	<% end %>
</div>

app/views/home/index.html.erb
<h1 class="text-center"></h1>
 
<div class="text-center">
<!-- 	<%= image_tag("trebWhite.png", :alt => "trebuchet") %> -->
<h3 class="text-center"> CALENDAR<hr>[Year, Month, Week, Day]</h3>
<div id="calendar"></div>
</div>
<hr>